services:
  event-app-api:
    build:
      context: .
    container_name: event-app-api
    ports:
      - 3000
    environment:
      DB_URL: ${DB_URL}
      SECRET_KEY: ${SECRET_KEY}
      CRYPTO_KEY: ${CRYPTO_KEY}
