services:
  event-app-api:
    build:
      context: .
    container_name: event-app-api
    ports:
      - "3000:3000"
    environment:
      DB_URL: postgres://user:1234@postgres:5432/db
      SECRET_KEY: ${SECRET_KEY}
      CRYPTO_KEY: ${CRYPTO_KEY}
    networks:
      - shared-network
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: user
      POSTGRES_DB: db
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge
