services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: user
      POSTGRES_DB: db
    networks:
      - app-network

  smtp4dev:
    image: rnwood/smtp4dev
    container_name: smtp4dev
    ports:
      - "5000:80" # Web interface
      - "2525:25" # SMTP port
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
